name: setup-aws-amplify tests

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches: ["main"]
    paths: ["action.yml", ".github/workflows/tests.yml"]

jobs:
  setup-test:
    name: Setup with defaults
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: test-action
      - name: Setup @aws-amplify/cli@latest
        uses: ./test-action
  setup-node-version:
    name: Setup with node version 14
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: test-action
      - name: Setup @aws-amplify/cli@latest
        uses: ./test-action
        with:
          node_version: "14"
  setup-amplify-version:
    name: Setup with cli version 7.6.22
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: test-action
      - name: Setup @aws-amplify/cli@7.6.22
        uses: ./test-action
        with:
          cli_version: "7.6.22"
  setup-with-cache-first-run:
    name: Setup with cache enabled (first run)
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: test-action
      - name: Setup @aws-amplify/cli@latest
        uses: ./test-action
        with:
          cache_dependencies: "true"
  setup-with-cache-second-run:
    name: Setup with cache enabled (first run)
    needs: setup-with-cache-first-run
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: test-action
      - name: Setup @aws-amplify/cli@latest
        uses: ./test-action
        with:
          cache_dependencies: "true"
